app/config/AppConfig.scala, app/controllers/ETMPController.scala, app/services/ETMPService.scala, conf/application.conf, it/connectors/ETMPConnectorISpec.scala, it/controllers/ETMPControllerISpec.scala, it/services/ETMPServiceISpec.scala, it/utils/ETMPWiremock.scala, it/utils/IntegrationSpecCommonBase.scala, test/config/AppConfigSpec.scala, test/controllers/ETMPControllerSpec.scala, test/services/ETMPServiceSpec.scala
Waiting on #6 to be merged first.
=> [PRM-151-B] - Continuation of connector call and tests

app/models/point/PenaltyPoint.scala, it/controllers/ETMPControllerISpec.scala, it/utils/IntegrationSpecCommonBase.scala, test/base/SpecBase.scala, test/models/ETMPPayloadSpec.scala, test/models/point/PenaltyPointSpec.scala
Added points will not have penalty periods.
=> [PRM-227] - Made the period optional

app/config/AppConfig.scala, app/connectors/AppealsConnector.scala, app/controllers/AppealsController.scala, app/services/ETMPService.scala, conf/app.routes, it/connectors/AppealsConnectorISpec.scala, it/controllers/AppealsControllerISpec.scala, it/utils/AppealWiremock.scala, test/config/AppConfigSpec.scala, test/connectors/AppealsConnectorSpec.scala, test/controllers/AppealsControllerSpec.scala, test/services/ETMPServiceSpec.scala
Waiting on stub and frontend change
=> [PRM-364] - Added enrolment key to appeal submission URL

app/controllers/ETMPController.scala, it/controllers/ETMPControllerISpec.scala, it/utils/DatastreamWiremock.scala, it/utils/IntegrationSpecCommonBase.scala, test/controllers/ETMPControllerSpec.scala
=> [PRM-569] - Send UserHasPenalties audit when > 0 penalties present

app/config/AppConfig.scala, app/connectors/ComplianceConnector.scala, app/connectors/parsers/DESComplianceParser.scala, app/controllers/ComplianceController.scala, app/featureSwitches/FeatureSwitch.scala, app/models/compliance/CompliancePayloadObligationAPI.scala, app/services/ComplianceService.scala, app/services/ETMPService.scala, conf/app.routes, conf/application.conf, it/connectors/ComplianceConnectorISpec.scala, it/controllers/ComplianceControllerISpec.scala, it/services/ComplianceServiceISpec.scala, it/utils/ComplianceWiremock.scala, it/utils/IntegrationSpecCommonBase.scala, test/config/AppConfigSpec.scala, test/connectors/ComplianceConnectorSpec.scala, test/connectors/parsers/DESComplianceParserSpec.scala, test/controllers/AppealsControllerSpec.scala, test/controllers/ComplianceControllerSpec.scala, test/models/compliance/CompliancePayloadObligationAPISpec.scala, test/services/ComplianceServiceSpec.scala
https://github.com/hmrc/app-config-base/pull/6417
=> [PRM-828] - Added connector + parser + endpoint for getObligationAPI

app/config/AppConfig.scala, app/connectors/ComplianceConnector.scala, app/connectors/PEGAConnector.scala, conf/application.conf, test/connectors/ComplianceConnectorSpec.scala
PR to combine EIS bearer tokens + environment config ready for adding EIS bearer token in QA
App config PRs to go with changes:
https://github.com/hmrc/app-config-qa/pull/14186
https://github.com/hmrc/app-config-production/pull/13763
=> PRM Combined EIS Bearer Token + Environment Config

app/controllers/AppealsController.scala, test/connectors/v2/FinancialDetailsConnectorSpec.scala, test/controllers/AppealsControllerSpec.scala, test/models/v2/GetPenaltyDetailsSpec.scala
=> [PRM-1219] - Changed casing of caseID

app/models/auditing/v2/UserHasPenaltyAuditModel.scala, app/models/v3/getPenaltyDetails/latePayment/LPPDetails.scala, app/models/v3/getPenaltyDetails/lateSubmission/LSPDetails.scala, it/services/GetPenaltyDetailsServiceISpec.scala, it/utils/ETMPWiremock.scala, test/models/auditing/v2/UserHasPenaltyAuditModelSpec.scala, test/models/v3/getPenaltyDetails/GetPenaltyDetailsSpec.scala, test/models/v3/getPenaltyDetails/latePayment/LPPDetailsSpec.scala, test/models/v3/getPenaltyDetails/latePayment/LatePaymentPenaltySpec.scala, test/models/v3/getPenaltyDetails/lateSubmission/LSPDetailsSpec.scala, test/models/v3/getPenaltyDetails/lateSubmission/LateSubmissionPenaltySpec.scala, test/services/GetPenaltyDetailsServiceSpec.scala
Changed some of the model types as well :)
=> [PRM-1275] - Added new audit model for new 1812 API

app/connectors/parsers/v3/getPenaltyDetails/GetPenaltyDetailsParser.scala, app/models/PagerDutyHelper.scala, test/connectors/parsers/v3/getPenaltyDetails/GetPenaltyDetailsParserSpec.scala, test/models/PagerDutyHelperSpec.scala
Alert config PR: https://github.com/hmrc/alert-config/pull/2422
=> [PRM-1328] - Added alerting for 422 from ETMP

app/config/AppConfig.scala, app/config/featureSwitches/FeatureSwitch.scala, app/config/featureSwitches/FeatureSwitching.scala, app/controllers/APIController.scala, app/controllers/AppealsController.scala, app/controllers/testOnly/FeatureSwitchController.scala, app/services/ComplianceService.scala, conf/application.conf, conf/testOnlyDoNotUseInAppConf.routes, it/connectors/ComplianceConnectorISpec.scala, it/connectors/ETMPConnectorISpec.scala, it/connectors/PEGAConnectorISpec.scala, it/connectors/v2/FinancialDetailsConnectorISpec.scala, it/connectors/v2/PenaltyDetailsConnectorISpec.scala, it/connectors/v3/getPenaltyDetails/GetPenaltyDetailsConnectorISpec.scala, it/controllers/APIControllerISpec.scala, it/controllers/AppealsControllerISpec.scala, it/controllers/ComplianceControllerISpec.scala, it/services/ComplianceServiceISpec.scala, it/utils/IntegrationSpecCommonBase.scala, test/config/AppConfigSpec.scala, test/config/featureSwitches/FeatureSwitchSpec.scala, test/connectors/PEGAConnectorSpec.scala, test/controllers/APIControllerSpec.scala, test/controllers/AppealsControllerSpec.scala, test/services/ComplianceServiceSpec.scala
Use either CURL or config value to set feature switch
=> [PRM-1365] - Revised feature switch implementation

app/models/v3/getFinancialDetails/DocumentDetails.scala, app/models/v3/getFinancialDetails/FinancialDetails.scala, app/models/v3/getFinancialDetails/FinancialItem.scala, app/models/v3/getFinancialDetails/GetFinancialDetails.scala, it/connectors/v2/FinancialDetailsConnectorISpec.scala, test/models/v3/getFinancialDetails/DocumentDetailsSpec.scala, test/models/v3/getFinancialDetails/FinancialDetailsSpec.scala, test/models/v3/getFinancialDetails/FinancialItemSpec.scala, test/models/v3/getFinancialDetails/GetFinancialDetailsSpec.scala
Assuming we aren't using balanceDetails, codingDetails and taxPayerDetails. Will create a subtask as a placeholder just in case.
=> [PRM-1417] - Copied financial details to v3 and made some amendments for 1811 API

app/controllers/AppealsController.scala, app/models/appeals/MultiplePenaltiesData.scala, conf/app.routes, it/controllers/AppealsControllerISpec.scala, test/controllers/AppealsControllerSpec.scala, test/models/appeals/MultiplePenaltiesDataSpec.scala
Returns OK when there is multiple penalties
Returns NO CONTENT when there is only one penalty under this principal charge
=> [PRM-1583] - Find multiple penalties for a principal charge

app/models/auditing/UserHasPenaltyAuditModel.scala, test/models/auditing/UserHasPenaltyAuditModelSpec.scala
Page:
Audit:
(count of unpaid penalties is wrong and will be actioned under PRM-1773)
=> [PRM-1772] - Added partially paid penalties to UserHasPenalty audit

app/models/auditing/UserHasPenaltyAuditModel.scala, test/models/auditing/UserHasPenaltyAuditModelSpec.scala
=> [PRM-1777] - Added inactive penalty count to UserHasPenalty audit

app/controllers/APIController.scala, app/controllers/PenaltiesFrontendController.scala, app/models/auditing/UserHasPenaltyAuditModel.scala, app/utils/DateHelper.scala, app/utils/RegimeHelper.scala, test/controllers/APIControllerSpec.scala, test/controllers/PenaltiesFrontendControllerSpec.scala, test/models/auditing/UserHasPenaltyAuditModelSpec.scala, test/utils/DateHelperSpec.scala, test/utils/RegimeHelperSpec.scala
Page:
Audit:
Audit (TTP not active):
=> [PRM-1779] - Add TTP info to audit

app/connectors/parsers/AppealsParser.scala, app/controllers/AppealsController.scala, conf/app.routes, it/controllers/AppealsControllerISpec.scala, project/plugins.sbt, test/connectors/parsers/AppealsParserSpec.scala, test/controllers/AppealsControllerSpec.scala
Added descriptive error messages to log at frontend
=> [PRM-2237] - Return error when appealing multiple penalties

app/controllers/AppealsController.scala, it/controllers/AppealsControllerISpec.scala, test/controllers/AppealsControllerSpec.scala
=> [PRM-2236] - Return 207 on successful appeal submission but failed file notification storage

app/models/auditing/UserHasPenaltyAuditModel.scala, test/models/auditing/UserHasPenaltyAuditModelSpec.scala
=> [PRM-2257] - Used long form names for PenaltyUserHasPenalty audit event

build.sbt, project/AppDependencies.scala, project/plugins.sbt
Server starts in dev and prod mode, AT's and PT's pass
=> [PRM-2195] - Upgrade dependencies

app/models/appeals/AppealSubmission.scala, test/models/appeals/AppealSubmissionSpec.scala
=> [PRM-2299] - Send 'lateAppeal' when appealing against obligation

app/config/featureSwitches/FeatureSwitch.scala, conf/application.conf, test/config/featureSwitches/FeatureSwitchSpec.scala
Creating as draft as PRM-2301 should be implemented first
=> PRM-2302 Remove old ReceiptDate Feature switch

app/config/featureSwitches/FeatureSwitch.scala, app/controllers/AppealsController.scala, app/services/AppealService.scala, conf/application.conf, test/config/featureSwitches/FeatureSwitchSpec.scala, test/controllers/AppealsControllerSpec.scala, test/services/AppealServiceSpec.scala
=> [PRM-SanitiseFileName] - Sanitised file name before sending downstream

app/services/AppealService.scala, app/utils/UUIDGenerator.scala, test/services/AppealServiceSpec.scala, test/utils/UUIDGeneratorSpec.scala
This reverts commit 5abd36646599e7d82b2089a26e082e416f070b65.
=> Revert "PRM-2782 Use File UpScan Reference for correlation ID (#286)"
